Implement temperature monitoring with direct sysfs access
nojhan/liquidprompt pull request #623
Opened 2020-10-02 02:38 UTC by rfc1036

I am proposing an implementation of temperature monitoring which does not require executing other binaries (as is being discussed in https://github.com/nojhan/liquidprompt/issues/607).
For the time being users need to set `LP_TEMP_HWMON` to a value like `hwmon4/temp1_input` after checking which sensor makes more sense for them, but with some more work it would not be hard to use e.g. the first CPU core as the default sensor.

2020-10-02 16:01 UTC, Rycieos requested changes
This looks quite good. What remains is to test this on many systems, test on MacOS and SunOS (I doubt it will work, I don't think they have the `/sys/` interface), and find what kernel version added this interface.

The other sticking point is right now Liquidprompt looks at all sensors (specifically their `temp1_input`) and displays the highest one. This only reads one sensor. I'd like to keep that multi-sensor functionality, or even better, have one function to get the highest CPU temp, and one for the highest GPU temp. This might not be possible "out of the box".

2020-10-02 16:18 UTC, rfc1036 commented
This is strictly Linux-only. The hwmon class has been introduced by the kernel a very long time ago, but drivers for specific hardware have been introduced in different releases.

The same algorithm which chooses the highest value reported can be implemented, but I would still want to be able to configure monitoring just a specific sensor. I do not have a system with a discrete GPU so I do not know if they report temperature using an hwmon class driver or what else.

2020-11-20 16:19 UTC, Rycieos commented
With the news in #633, I want to get this working more than ever.

This appears to be the documentation for this kernel interface:
https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface
I can't find any info on first supported version.

It all looks quite straightforward, except this bit:
> Some chips [...] report the temperature measurement as a voltage. Converting this voltage back to a temperature [...] must occur in user space.

This is troublesome for two reasons:
1. That means we need to convert, and if the kernel can't do it, what are the chances a shell script can?
2. I don't see anything in the docs describing how to tell if the interface is returning a temperature or a voltage.

Ignoring that issue, I see two other problems:
1. Your implementation doesn't have a default value. I want every data function to work out-of-the-box, without configuration.
2. Your implementation doesn't support reading from more than one input.

Here is my suggestion:
```bash
_lp_temp_hwmon() {
    [[ -e /sys/class/hwmon/ ]] || return

    local file temp highest_temp=0
    for file in /sys/class/hwmon/*/temp*_input; do
        IFS= read temp <"$file"
        (( temp > highest_temp )) && highest_temp=$temp
    done
    temperature=$((highest_temp / 1000))
}
```

I realize this removes the ability for a user to not read some inputs. I'm open to suggestions. Or here's another idea:
```bash
# Done when reading config:
# If array not already set
[[ -z ${LP_TEMP_INPUT_FILES[@]+x} ]] && LP_TEMP_INPUT_FILES=( /sys/class/hwmon/*/temp*_input )
...
_lp_temp_hwmon() {
    [[ -e /sys/class/hwmon/ ]] || return

    local file temp highest_temp=0
    for file in "${LP_TEMP_INPUT_FILES[@]}"; do
        IFS= read temp <"$file"
        (( temp > highest_temp )) && highest_temp=$temp
    done
    temperature=$((highest_temp / 1000))
}
```

Let's get some discussion going on this.

2020-11-20 16:53 UTC, Rycieos commented
I took a look at [psutil](https://pypi.org/project/psutil/), the leading Python library for reading sensors, and here is how they do it on Linux:

https://github.com/giampaolo/psutil/blob/a5eeaadb7fd07b855d7e9a98659ce102ab904ee4/psutil/_pslinux.py#L1239-L1260

So it seems that we could read:
```bash
LP_TEMP_INPUT_FILES=(
    /sys/class/hwmon/hwmon*/temp*_input
    # CentOS has an intermediate /device directory:
    /sys/class/hwmon/hwmon*/device/temp*_input
    /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_input
    # Older, fallback option
    /sys/class/thermal/thermal_zone*/temp
)
```

This gets more tricky, as by default, if the shell doesn't find any matches for the glob, it returns the string:
```bash
$ printf '%q\n' "${LP_TEMP_INPUT_FILES[@]}"
/sys/class/hwmon/hwmon0/temp1_input
/sys/class/hwmon/hwmon1/temp1_input
/sys/class/hwmon/hwmon2/temp1_input
/sys/class/hwmon/hwmon\*/device/temp\*_input
/sys/devices/platform/coretemp.\*/hwmon/hwmon\*/temp\*_input
/sys/class/thermal/thermal_zone0/temp
```

But the good news is that psutil ignores the possibility of hwmon/temp returning a voltage instead of Celsius, so I guess we can too?

2022-05-20 19:50 UTC, closed without merging