Unify project name as "Liquid Prompt" in docs (spelled as two words)
nojhan/liquidprompt pull request #677
Opened 2021-06-28 05:58 UTC by ottok

On the front page README.md the project name is spelled "Liquid Prompt" as two words. This PR suggests to use that spelling across all project documentation.

2021-06-28 15:54 UTC, Rycieos commented
In my opinion, I think it makes sense as one word. The project ID is also one word; if it was two words, I would think it would be `liquid-prompt`. I would rather see any instances of "Liquid prompt" changed to "Liquidprompt" than this.

But @nojhan named it originally, so what would you like to see?

2021-06-28 16:16 UTC, augmentedfourth commented
Also note that the package name in homebrew (and I think other distribution mechanisms) is a single word, un-capitalized... just like the file name of the script itself. I'll defer to @nojhan as well, but as someone who's used this tool for over a decade "Liquid Prompt" just looks jarring.

2021-06-28 16:17 UTC, nojhan commented
That's a thought question. Do someone have access to some SEO tools to check which name leads to the largest search engine share (out of existing hits)?

2021-06-28 16:31 UTC, Rycieos commented
> Do someone have access to some SEO tools to check which name leads to the largest search engine share

I'm no SEO expert, but some quick digging leads to the following:
1. "Liquid prompt" has more than 10 times the "hits" than "Liquidprompt" does, but that is not a fair comparison. The space means it is two separate search terms, and you get a ton of false positive hits.
2. "Liquid prompt" hits mostly on blog posts about the project (so many blog posts, wow).
3. "Liquidprompt" hits mostly on documentation and packaging indexes.
4. "Liquidprompt" hits on pages with only the string "Liquid prompt" in the page.

Based on this, I think:
* Because of 4, searching with the string "liquidprompt" will hit both forms, while "liquid prompt" won't always.
* Documentation is probably the first thing we want users to find.
* Because of 1, we don't want users to find unrelated pages.

I think that "Liquidprompt" is better for SEO.

2021-06-29 06:43 UTC, nojhan commented
Seems like a good point to me :)

On Mon, Jun 28, 2021 at 6:31 PM Mark Vander Stel ***@***.***>
wrote:

> Do someone have access to some SEO tools to check which name leads to the
> largest search engine share
>
> I'm no SEO expert, but some quick digging leads to the following:
>
>    1. "Liquid prompt" has more than 10 times the "hits" than
>    "Liquidprompt" does, but that is not a fair comparison. The space means it
>    is two separate search terms, and you get a ton of false positive hits.
>    2. "Liquid prompt" hits mostly on blog posts about the project (so
>    many blog posts, wow).
>    3. "Liquidprompt" hits mostly on documentation and packaging indexes.
>    4. "Liquidprompt" hits on pages with only the string "Liquid prompt"
>    in the page.
>
> Based on this, I think:
>
>    - Because of 4, searching with the string "liquidprompt" will hit both
>    forms, while "liquid prompt" won't always.
>    - Documentation is probably the first thing we want users to find.
>    - Because of 1, we don't want users to find unrelated pages.
>
> I think that "Liquidprompt" is better for SEO.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nojhan/liquidprompt/pull/677#issuecomment-869831133>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACFSULFQ3O5TVIFXFJZE4LTVCPW3ANCNFSM47NH6NYA>
> .
>

2021-06-29 07:12 UTC, ottok commented
I'll wait for a week for further feedback and if this is the decision, I'll revert the PR to do the change for all current Liquid Prompt into Liquidprompt.

2021-07-01 13:29 UTC, dolmen commented
As someone who has contributed to this mess, my preference was Liquid Prompt as the project name and `liquidprompt` as the command to invoke it.

But as a former maintainer, consider my vote as neutral if votes are involved.

2021-07-18 03:27 UTC, ottok commented
When looking at pages that Google finds on "liquidprompt" they are all pages that reference the package name, not the project name. As soon as you start to get results about blog posts that decribe the project, everybody seem to write about "Liquid Prompt" – two separate words, and both capitalized. I agree with that and I think it is also better English (though I am not a native speaker). One of the search results with "liquidprompt" even yields "Liquid Prompt", because that blog post is so popular.

Thus, I leave my PR leaning on "Liquid Prompt".


![image](https://user-images.githubusercontent.com/668724/126054585-b3e21e84-ca36-4dba-83f3-fa20cfe02f8f.png)

vs

![image](https://user-images.githubusercontent.com/668724/126054599-b8d749ae-a744-49f3-996b-f45c1d033ef2.png)

2021-07-18 03:29 UTC, ottok commented
I also checked [Google Trends](https://trends.google.com/trends/explore?date=all&q=liquid%20prompt,liquidprompt). The name "Liquid Prompt" is more popular than spelled together, but the search volume is so low that the difference is not significant.

![image](https://user-images.githubusercontent.com/668724/126054704-5e09676b-495d-455d-aa2f-1b30ae4cdc9a.png)

2021-07-29 16:01 UTC, Rycieos commented
Sorry for the radio silence on this. I'm not sure what the path forward should be, since we have a few on each side of the camp, and @nojhan seems to be fine either way. Ideally we would get some other opinions on this, but I realize that leaving this sitting open forever is not ideal either.

2021-07-29 16:07 UTC, ottok commented
Don't worry, leaving the issue open is fine to me, no hurry here :)

In this case taking some time to collect feedback and think about it is a
good thing.

>

2022-08-22 08:04 UTC, nojhan commented
Looking at the search engine results, I think "Liquid Prompt" would better match what the actual users are using to refer to the project.

This is a key point in my opinion, because we are facing competitors that have less interesting features and design, and still surprisingly seem to be more popular. We definitely need to reach the users *in their own words*.

Also, it emphasizes one of the key feature of the design, which is to actually be *liquid*. It is probably worth it to use the adjective as a keyword, and I think having it separated helps. One could even use "*the* Liquid Prompt", so as to emphasize even more.

It doesn't seem like a big deal to have the command/repository keeping the one-word version, I think most of people would understand, especially if the official website use the two-words version.

2022-08-22 14:50 UTC, Rycieos requested changes
Ok, sounds like a close enough consensus then. I agree, let's unify the name.

@ottok, if you could fix these small issues I've pointed out, and maybe squash and rebase, I'll merge this in.

2022-08-22 14:50 UTC, Rycieos commented on docs/theme/included/powerline.rst
>  --------------------------
Line needs expanding to match header.

2022-08-22 14:50 UTC, Rycieos commented on docs/theme/included/powerline.rst
>  --------------------------
Line needs expanding to match header.

2022-08-22 14:50 UTC, Rycieos commented on docs/theme/included/alternate_vcs.rst
>  --------------------------
Line needs expanding to match header.

2022-08-22 14:50 UTC, Rycieos commented on docs/index.rst
>  ========================================
Line needs expanding to match header.

2022-08-22 14:50 UTC, Rycieos commented on docs/config.rst
> +     a directory named ``~/MyProjects/Liquid Prompt/tests``, it will be shortened
This isn't a explicit name reference, but a directory path. Probably should leave this one as it was, even though it is only an example.

2022-08-22 19:48 UTC, ottok commented
Sure, I can refresh to use "Liquid Prompt" everywhere as agreed today.

2022-08-23 05:54 UTC, ottok commented
Fixed all items commented and rebased on latest master.

2022-08-23 14:42 UTC, Rycieos approved these changes
Thanks @ottok!

2022-08-23 14:42 UTC, merged