Feat+error meaning
nojhan/liquidprompt pull request #745
Opened 2022-10-16 18:32 UTC by nojhan

Basically displays the (guessed) meaning of the last error code (feature request #729).

Separated in two commits, so that you may allow a more or less granular level of details.

First commit: adds the core feature.
- Use a set of reasonably common error codes on POSIX systems
  (but is LP used out of a POSIX env?).
- Use the color than lp_error (namely LP_COLOR_ERR).
- Use a separated LP_ENABLE_ERROR_MEANING.
- Put in the default theme right after the error code.
- Code would be very much simpler/configurable with Bash 4's associative arrays,
  but here use a case switch with non-configurable error meanings.

Second commit: let the user decide the level of guess for error meaning.
- Adds LP_ENABLE_ERROR_MEANING_EXTENDED to allow for a larger set of error codes.

2022-10-23 15:58 UTC, Rycieos requested changes
Looks good in general, just a few issues.

2022-10-23 15:58 UTC, Rycieos commented on docs/config.rst
> +.. attribute:: LP_ENABLE_ERROR_MEANING
This config variable is never checked, so the feature is always enabled.

2022-10-23 15:58 UTC, Rycieos commented on docs/config.rst
> +   See also: :attr:`LP_COLOR_ERR`.
This need a mention that it will have no effect if `LP_ENABLE_ERROR_MEANING` is disabled.

2022-10-23 15:58 UTC, Rycieos commented on liquidprompt
> +    _lp_error || return "$?"
The issue with checking for the error code in this way is that if `LP_ENABLE_ERROR` is false, this function will be disabled as well. I think it makes sense to allow users to enable error meanings without enabling the printing of the raw code.

I would change this check to this:
```suggestion
    (( LP_ENABLE_ERROR_MEANING )) || return 2
    (( lp_error != 0 )) || return 1
```

2022-10-24 13:18 UTC, nojhan commented
Do I squash all commits into one ? (i.e. do you want to keep the extended error meaning setup?)

2022-10-24 15:25 UTC, Rycieos requested changes
Looks good now.

I missed that question the first time, sorry. I do not have much of an opinion. Clearly you intended for both bits to be part of the feature, so it would be fine in once commit. But if you want it as separate, I'm fine with that.

But no matter what, squash away the extra commits from the fixes and docs.

2022-10-24 16:42 UTC, nojhan commented
The two commits were only there to make it easy to just have a single config, if you're OK with the "extended" config, I'll squash everything.

2022-10-25 15:52 UTC, Rycieos requested changes
Yeah, squash down to 1.

2022-10-25 15:52 UTC, Rycieos commented on liquidprompt
> +    (( _lp_error != 0 )) || return 1
> ./liquidprompt: line 1331: _lp_error: unbound variable

```suggestion
    (( lp_error != 0 )) || return 1
```

2022-10-27 15:34 UTC, Rycieos approved these changes

2022-10-27 15:35 UTC, merged