feat: adds a RAM sensor
nojhan/liquidprompt pull request #770
Opened 2023-02-27 18:30 UTC by nojhan

Displays a (colored) mark (and a percentage) when the available of RAM goes below a threshold.

Refs: #52

# Technical checklist:

- code follows our [shell standards](https://github.com/nojhan/liquidprompt/wiki/Shell-standards):
    - [x] correct use of `IFS`
    - [x] careful quoting
    - [x] cautious array access
    - [x] portable array indexing with `_LP_FIRST_INDEX`
    - [x] printing a "%" character is done with `_LP_PERCENT`
    - [x] functions/variable naming conventions
    - [x] functions have local variables
    - [x] data functions have optimization guards (early exits)
    - [x] subshells are avoided as much as possible
    - [x] string substitutions may be done differently in Bash and Zsh (use `_LP_SHELL_*`)
- tests and checks have been added, ran, and their warnings fixed:
    - [x] unit tests have been updated (see `tests/test_*.sh` files)
    - [x] ran `test.sh`
    - [x] ran `shellcheck.sh` (requires [shellcheck](https://github.com/koalaman/shellcheck#user-content-installing)).
- documentation have been updated accordingly:
    - [x] functions and attributes are documented in alphabetical order
    - [x] new sections are documented in the default theme
    - [x] tag `.. versionadded:: X.Y` or `.. versionchanged:: Y.Z`
    - [x] functions signatures have arguments, returned code, and set value(s)
    - [x] attributes have types and defaults
    - [x] ran `docs/docs-lint.sh` (requires Python 3 and `requirements.txt`
          installed (`cd docs/; python3 -m venv venv; . venv/bin/activate; pip install -r requirements.txt`))

2023-02-28 18:47 UTC, nojhan commented
Looking back at #730, I am now wondering whether handling the percentage of available memory is the right approach. Should we rather display/configure values in human readable amount? (branch `feat/disk` have `__lp_bytes_to_human`, for instance).

2023-02-28 19:21 UTC, Rycieos requested changes
I think it makes sense to support both percentages and absolute values as display. And ideally we would collapse into MiB or KiB to prevent the segment from being too large.

2023-02-28 19:21 UTC, Rycieos commented on liquidprompt
> +            IFS=$' ' read -r _ _ _ _ _ _ _ page_size _ <<< "$stat"
Don't need the $ without escape chars
```suggestion
            IFS=' ' read -r _ _ _ _ _ _ _ page_size _ <<< "$stat"
```

2023-03-04 15:09 UTC, nojhan commented on liquidprompt
> +            done < $_LP_LINUX_RAM_FILE
I don't see this warning with shellcheck 0.7.0 :disappointed:

2023-03-04 15:12 UTC, nojhan commented
I am waiting for PR #771 to be finished to get back at this, so that RAM and HD management would be consistent.

2023-07-22 17:54 UTC, nojhan commented
Since PR #771 has been merged, I rebased this one on top of it, using a similar implementation.

2023-07-24 15:24 UTC, Rycieos requested changes
I'm not sure what you did, but somehow you replicated all of the commits on master onto your branch. Which obviously has a lot of conflicts. Probably the way to fix this is something like
```bash
git checkout -b wip/mem f95a43f
git rebase origin/master
```
There will be a few conflicts (because of feat/disk), but they are easy to fix. I did exactly that and pushed the `wip/mem` branch, you can `git reset --hard origin/wip/mem` if you think it looks good.

I didn't look at the diff too hard (since reviewing that on GitHub is much easier), but I did notice and wanted to point out to remember to move the `if [ -n "${ZSH_VERSION-}" ] ...` block to the top of the test file after the `set -u` line.

2023-07-26 10:15 UTC, nojhan commented
Every time I try an acrobatic rebase, I get problems instead of solution…

This should be good now, here is what I did:
```sh
git co master
git co -b feat/mem2
git cherry-pick 49201b05da985173622ba364e8d79e322c6799da
# Merge & fix missing stuff.
git co feat/mem
git reset --hard origin/master
git cherry-pick efa6f8e6566ea0b0af679a6b5c2f7c1990719475
git push -f
```

2023-08-01 20:23 UTC, Rycieos requested changes
Looking real good. Only one Zsh 5.0 bug. And a few `IFS=$' '`s that could be `IFS=' '` instead.

And sorry for the delay. My development server's main drive failed, and I had to reinstall the OS.

2023-08-01 20:23 UTC, Rycieos commented on docs/config.rst
> +   The precision of the available space can be configured with
```suggestion
   The precision of the displayed available space can be configured with
```

2023-08-01 20:23 UTC, Rycieos commented on liquidprompt
> +            local stat=$(vm_stat 2>/dev/null)
Needs quoting to not fail on Zsh 5.0
```suggestion
            local stat="$(vm_stat 2>/dev/null)"
```

2023-08-04 17:55 UTC, nojhan commented
No problem, there is no hurry :-)

How should we handle the Zsh 5 bug?

2023-08-05 19:52 UTC, Rycieos commented
You already fixed it. A squash and I'll approve.

2023-08-25 19:27 UTC, Rycieos approved these changes

2023-08-25 19:27 UTC, merged

2023-08-29 15:54 UTC, nojhan commented
Great!